# Generated by Django 5.1.4 on 2025-01-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("softskills", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order", "-is_active", "-created_at"],
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
            },
        ),
        migrations.AddField(
            model_name="historicalsoftskilltraining",
            name="max_range",
            field=models.PositiveIntegerField(default=0, verbose_name="max range"),
        ),
        migrations.AddField(
            model_name="historicalsoftskilltraining",
            name="min_range",
            field=models.PositiveIntegerField(default=0, verbose_name="min range"),
        ),
        migrations.AddField(
            model_name="softskilltraining",
            name="max_range",
            field=models.PositiveIntegerField(default=0, verbose_name="max range"),
        ),
        migrations.AddField(
            model_name="softskilltraining",
            name="min_range",
            field=models.PositiveIntegerField(default=0, verbose_name="min range"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="grade",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="grade"
            ),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="grade",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="grade"
            ),
        ),
        migrations.AlterField(
            model_name="historicalquestionnaire",
            name="grade",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="grade"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="option",
            field=models.CharField(
                choices=[
                    ("STRONGLY_DISAGREE", "Totalmente en desacuerdo"),
                    ("DISAGREE", "En desacuerdo"),
                    ("NEUTRAL", "Ni de acuerdo / ni en desacuerdo"),
                    ("AGREE", "Algo de acuerdo"),
                    ("STRONGLY_AGREE", "Totalmente de acuerdo"),
                ],
                max_length=20,
                verbose_name="option",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="grade",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="grade"
            ),
        ),
    ]
