# Generated by Django 5.1.4 on 2025-01-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("softskills", "0003_remove_historicalsoftskilltraining_max_range_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="softskill",
            options={
                "ordering": ["-is_active", "created_at"],
                "verbose_name": "Habilidad Blanda",
                "verbose_name_plural": "Habilidades Blandas",
            },
        ),
    ]
