# Generated by Django 5.1.4 on 2025-01-28 05:01

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_historicalprofile_display_name_and_more"),
        ("softskills", "0004_alter_softskill_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="softskills.questionnaire",
                verbose_name="questionnaire",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalQuestionnaireGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("idx", models.BigIntegerField(default=1)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletion_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="deletion ip"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "creation_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="creation ip"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last update at"
                    ),
                ),
                (
                    "update_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="update ip"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="is current"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "attendee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="profiles.profile",
                        verbose_name="attendee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Grupo de cuestionarios",
                "verbose_name_plural": "historical Grupos de cuestionarios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="QuestionnaireGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("idx", models.BigIntegerField(default=1)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletion_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="deletion ip"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "creation_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="creation ip"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last update at"
                    ),
                ),
                (
                    "update_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="update ip"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="is current"),
                ),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questionnaire_groups",
                        to="profiles.profile",
                        verbose_name="attendee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_create_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de cuestionarios",
                "verbose_name_plural": "Grupos de cuestionarios",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="historicalquestionnaire",
            name="questionnaire_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="softskills.questionnairegroup",
                verbose_name="questionnaire group",
            ),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="questionnaire_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questionnaires",
                to="softskills.questionnairegroup",
                verbose_name="questionnaire group",
            ),
        ),
    ]
