from django.db import models


class LikertOptions(models.TextChoices):
    STRONGLY_DISAGREE = "STRONGLY_DISAGREE", "STRONGLY DISAGREE"
    DISAGREE = "DISAGREE", "DISAGREE"
    NEUTRAL = "NEUTRAL", "NEUTRAL"
    AGREE = "AGREE", "AGREE"
    STRONGLY_AGREE = "STRONGLY_AGREE", "STRONGLY AGREE"
