# Generated by Django 5.1.4 on 2025-01-24 03:56

import apps.files.models
import apps.files.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("idx", models.BigIntegerField(default=1)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletion_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="deletion ip"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "creation_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="creation ip"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last update at"
                    ),
                ),
                (
                    "update_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="update ip"
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="observations",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "path",
                    models.FileField(
                        max_length=200,
                        upload_to=apps.files.models.file_upload_path,
                        validators=[
                            apps.files.validators.validate_file_size,
                            apps.files.validators.validate_file_path_length,
                        ],
                    ),
                ),
                ("source_id", models.UUIDField(verbose_name="source_id")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Documento"),
                            ("LOGO", "Logo"),
                            ("PHOTO", "Photo"),
                        ],
                        max_length=30,
                        verbose_name="category",
                    ),
                ),
                (
                    "reference_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="reference_link"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                        verbose_name="content_type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_create_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "file",
                "verbose_name_plural": "files",
                "ordering": ["-is_active", "-created_at", "source_id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFile",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("idx", models.BigIntegerField(default=1)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "deletion_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="deletion ip"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "creation_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="creation ip"
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last update at"
                    ),
                ),
                (
                    "update_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="update ip"
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="observations",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "path",
                    models.TextField(
                        max_length=200,
                        validators=[
                            apps.files.validators.validate_file_size,
                            apps.files.validators.validate_file_path_length,
                        ],
                    ),
                ),
                ("source_id", models.UUIDField(verbose_name="source_id")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Documento"),
                            ("LOGO", "Logo"),
                            ("PHOTO", "Photo"),
                        ],
                        max_length=30,
                        verbose_name="category",
                    ),
                ),
                (
                    "reference_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="reference_link"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="content_type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical file",
                "verbose_name_plural": "historical files",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
